/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfigSettings: typeof import('./components/ConfigSettings.vue')['default']
    PasswordSettings: typeof import('./components/PasswordSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    SectionSelection: typeof import('./components/SectionSelection.vue')['default']
    UpdateUserModal: typeof import('./components/UpdateUserModal.vue')['default']
    UsersList: typeof import('./components/UsersList.vue')['default']
    UsersSettings: typeof import('./components/UsersSettings.vue')['default']
  }
}
